run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable:
    - typecheck
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - revive
    - gosec
    - misspell
    - unconvert
    - gocyclo
    - dupl
    - gofumpt
    - whitespace
    - wsl
    - nlreturn
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true
      - name: var-naming
        disabled: false